server:
  port: 9696
  servlet:
    session.timeout: 60000
  undertow:
     io-threads: 16
     worker-threads: 256
     buffer-size: 1024
     buffer-per-region: 1024
     direct-buffers: true
logging:
  level.root: info
  level.org.springframework: warn
  level.app: info
swagger:
 enabled: true
